spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/selvasingh/spring-microservices-performance-config.git
        native:
          search-locations: classpath:.
  profiles:
    active: native
